//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hetrogiupquyetdinh.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HeTroGiupQuyetDinh1Entities : DbContext
    {
        public HeTroGiupQuyetDinh1Entities()
            : base("name=HeTroGiupQuyetDinh1Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DiemChuan> DiemChuans { get; set; }
        public virtual DbSet<Khoi> Khois { get; set; }
        public virtual DbSet<SoThich> SoThiches { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Truong> Truongs { get; set; }
        public virtual DbSet<Vien> Viens { get; set; }
        public virtual DbSet<Vien_SoThich> Vien_SoThich { get; set; }
        public virtual DbSet<DiemCacNam> DiemCacNams { get; set; }
    }
}
