//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hetrogiupquyetdinh.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DiemCacNam
    {
        public int IDVien { get; set; }
        public double Nam2014 { get; set; }
        public double Nam2015 { get; set; }
        public double Nam2016 { get; set; }
        public double Nam2017 { get; set; }
    
        public virtual Vien Vien { get; set; }
    }
}
