//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hetrogiupquyetdinh.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DiemChuan
    {
        public int Id { get; set; }
        public Nullable<int> IdVien { get; set; }
        public Nullable<int> Nam { get; set; }
        public Nullable<double> DiemChuan1 { get; set; }
        public Nullable<int> Chitieu { get; set; }
    
        public virtual Vien Vien { get; set; }
    }
}
