//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hetrogiupquyetdinh.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vien_SoThich
    {
        public int IdVien { get; set; }
        public int IdSoThich { get; set; }
        public int Diem { get; set; }
    
        public virtual SoThich SoThich { get; set; }
        public virtual Vien Vien { get; set; }
    }
}
