//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hetrogiupquyetdinh.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vien
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Vien()
        {
            this.DiemChuans = new HashSet<DiemChuan>();
            this.DiemCacNams = new HashSet<DiemCacNam>();
            this.Vien_SoThich = new HashSet<Vien_SoThich>();
        }
    
        public int Id { get; set; }
        public string Ten { get; set; }
        public Nullable<int> TruongID { get; set; }
        public Nullable<int> KhoiID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DiemChuan> DiemChuans { get; set; }
        public virtual Khoi Khoi { get; set; }
        public virtual Truong Truong { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DiemCacNam> DiemCacNams { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Vien_SoThich> Vien_SoThich { get; set; }
    }
}
